### ISSUE TITLE
Missing `ngram_size` param in calling code

### ISSUE THREAD

**Issue by tiendung** [mindslab-ai/pnlp-mixer#2]
https://github.com/mindslab-ai/pnlp-mixer/blob/2e13161a7fc6ac8ee07989f3c22359480485e24b/projection.py#L91

**Comment by tonyswoo** [comment]
My bad. 

I hardcoded the value of `ngram_size` to 3 when I first wrote the code, per the manuscript, and later changed it to a configurable value. I guess I forgot to update some parts of the code. 

This issue should be fixed in the latest commit. I also added a new command line argument for `projection.py` for `ngram_size` and updated the README file accordingly. 

Feel free to leave additional comments if the issue still persists.

**Comment by tiendung** [comment]
Thank you!
